import * as sm from '../js/state-machine.js';
const assert = (c,m)=>{ if(!c){ console.error('FAIL:',m); process.exitCode=1;} else console.log('ok:',m); };
assert(sm.intensityTier(2)==='L1','tier L1');
assert(sm.intensityTier(5)==='L2','tier L2');
assert(sm.intensityTier(9)==='L3','tier L3');
const ac = sm.selectColors('angry',9); assert(ac['--ip-body-out']==='#543461','angry L3 color');
const mc = sm.selectColors('mixed',5); assert(mc['--ip-body-in']==='#a78bfa'&&mc.gradient,'mixed gradient');
assert(sm.resolveEmotionKey({emotion_primary:'愤怒'})==='angry','愤怒->angry');
assert(sm.resolveEmotionKey({emotion:['开心']})==='joy','开心->joy');
assert(sm.resolveEmotionKey({emotion_primary:'悲伤'})==='sad','悲伤->sad');
assert(sm.resolveEmotionKey({emotion_primary:'愤怒',emotion_secondary:'悲伤'})==='mixed','复合->mixed');
assert(sm.resolveEmotionKey({ip_state:'empathy_tears'})==='sad','empathy_tears->sad');
const n_listen = sm.resolveNode({route:'record'}); assert(n_listen.node==='listening'&&n_listen.state==='listening','listening node');
const n_recv = sm.resolveNode({route:'analyzing',receivingUntil:Date.now()+500,emotionKey:'angry',intensity:9}); assert(n_recv.node==='receiving'&&n_recv.bubble==='正在接住你的情绪','receiving node');
const n_emo = sm.resolveNode({route:'followup',emotionKey:'angry',intensity:9}); assert(n_emo.node==='emotion_render'&&n_emo.state==='angry'&&n_emo.colors['--ip-body-out']==='#543461','emotion_render angry');
const n_reply = sm.resolveNode({route:'followup',emotionKey:'anxious',intensity:5,aiReplying:true}); assert(n_reply.node==='ai_reply','ai_reply node');
const n_danger = sm.resolveNode({route:'followup',emotionKey:'angry',riskLevel:'high'}); assert(n_danger.node==='danger'&&n_danger.danger===true,'danger node');
const n_idle = sm.resolveNode({route:'say'}); assert(n_idle.node==='idle'&&n_idle.state==='idle','idle node');
const g = sm.gateByMotion(n_emo,false); assert(g.state==='idle'&&Object.keys(g.colors).length===0,'motion off -> idle static');
assert(sm.isIdleTimeout(Date.now()-200000)===true,'idle timeout');
assert(sm.isIdleTimeout(Date.now()-1000)===false,'not idle timeout');
console.log('SMOKE DONE');
